version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: smarthouse-postgres
    restart: always
    environment:
      POSTGRES_DB: smarthouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smarthouse_pgdata:/var/lib/postgresql/data

  backend:
    image: shevchenko04/smarthome-backend:latest
    container_name: smarthouse-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smarthouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_CORS_ALLOWED_ORIGIN: http://54.174.180.189
      APP_JWT_SECRET: mysupersecurejwtsecretkey12345678901234567890

  frontend:
    image: shevchenko04/smarthome-frontend:latest
    container_name: smarthouse-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  smarthouse_pgdata:
