spring.application.name=smart-house-backend-system

server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/smarthouse}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${APP_JWT_SECRET:8f4d2c1a9b7e6f5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f123456789abcdef}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
logging.level.org.springframework.security=DEBUG

app.mqtt.public-host=${APP_MQTT_PUBLIC_HOST:54.174.180.189}
app.mqtt.public-port=${APP_MQTT_PUBLIC_PORT:1883}

energy.price-per-kwh=${ENERGY_PRICE_PER_KWH:2.16}
# MQTT
mqtt.enabled=${MQTT_ENABLED:true}
mqtt.broker-url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.client-id=${MQTT_CLIENT_ID:smarthome-backend}
mqtt.username=${MQTT_USERNAME:}
mqtt.password=${MQTT_PASSWORD:}
mqtt.auto-reconnect=true
mqtt.clean-session=true


# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=orozobekovasezim.kg@gmail.com
spring.mail.password=dghdahxrjkoevldn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true