spring.application.name=smart-house-backend-system

spring.datasource.url=jdbc:postgresql://localhost:5433/smarthouse
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVGhpc0lzQVN1cGVyU2VjcmV0S2V5
app.jwt.expiration=86400000

app.cors.allowed-origin=http://localhost:4200