spring.application.name=smart-house-backend-system

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
logging.level.org.springframework.security=DEBUG

# MQTT
mqtt.enabled=${MQTT_ENABLED:false}
mqtt.host=${MQTT_HOST:localhost}
mqtt.port=${MQTT_PORT:1883}
mqtt.client-id=${MQTT_CLIENT_ID:smart-home-backend}
mqtt.username=${MQTT_USERNAME:}
mqtt.password=${MQTT_PASSWORD:}
mqtt.clean-session=${MQTT_CLEAN_SESSION:true}
mqtt.auto-reconnect=${MQTT_AUTO_RECONNECT:true}