name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t shevchenko04/smarthome-backend:latest .

      - name: Push backend image
        run: docker push shevchenko04/smarthome-backend:latest

      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/smarthome

            echo "🛑 Stop backend"
            docker compose stop backend || true

            echo "🗑 Remove backend container"
            docker compose rm -f backend || true

            echo "🧹 Remove old backend image"
            docker image rm shevchenko04/smarthome-backend:latest || true

            echo "⬇️ Pull new image"
            docker compose pull backend

            echo "🚀 Start backend"
            docker compose up -d backend
